-- Table [dbo].[campanas]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[campanas]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[campanas](
	[id] [smallint] IDENTITY(1,1) NOT NULL,
	[cliente] [varchar](50) NULL,
	[campana] [varchar](50) NULL,
	[sub_campana] [varchar](50) NULL,
 CONSTRAINT [PK__campanas__3213E83FC6C66ECE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__campanas__634D68D15AE6E3F1] UNIQUE NONCLUSTERED 
(
	[sub_campana] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
