-- Table [dbo].[CSV_ADH_Skills]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSV_ADH_Skills]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CSV_ADH_Skills](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[inicio_intervalo] [datetime] NULL,
	[id_skill] [smallint] NULL,
	[nombre_skill] [varchar](40) NULL,
	[entrantes] [smallint] NULL,
	[contestadas] [smallint] NULL,
	[contestadas_en_ns] [smallint] NULL,
	[contestadas_antes_10s] [smallint] NULL,
	[abandonadas] [smallint] NULL,
	[abandonadas_post_umbral] [smallint] NULL,
	[eliminadas_cola] [smallint] NULL,
	[conectadas] [smallint] NULL,
	[salientes] [smallint] NULL,
	[salientes_ext] [smallint] NULL,
	[retenidas] [smallint] NULL,
	[tiempo_acw] [int] NULL,
	[tiempo_total_asa] [int] NULL,
	[tiempo_acd] [int] NULL,
	[tiempo_total_abandono] [int] NULL,
	[tiempo_logueo] [int] NULL,
	[tiempo_prom_cola] [int] NULL,
	[tiempo_salida_ext] [int] NULL,
	[tiempo_acd_hold] [float] NULL,
	[tiempo_aux_total] [float] NULL,
	[tiempo_ring_total] [int] NULL,
	[tiempo_disponible] [int] NULL,
	[tiempo_muerto] [int] NULL,
	[tiempo_salientes] [int] NULL,
	[tiempo_retencion] [int] NULL,
	[llamadas_por_pos] [smallint] NULL,
	[prom_pos_con_personal] [float] NULL,
	[pct_nivel_servicio] [float] NULL,
	[pct_abandono] [float] NULL,
	[pct_abandono_post_umbral] [float] NULL,
	[pct_eficacia_contestadas] [float] NULL,
	[tiempo_prom_acd] [float] NULL,
	[velocidad_prom_respuesta] [float] NULL,
	[tiempo_prom_abandono] [float] NULL,
	[tmo_bruto] [smallint] NULL,
	[tmo_neto] [smallint] NULL,
	[otras_llamadas] [smallint] NULL,
	[ocupado_forzado] [smallint] NULL,
	[desconexion_forzada] [smallint] NULL,
	[flujo_entrada] [smallint] NULL,
	[flujo_salida] [smallint] NULL,
	[transf_salida] [smallint] NULL,
	[aban_0_5s] [smallint] NULL,
	[aban_5_10s] [smallint] NULL,
	[aban_10_15s] [smallint] NULL,
	[aban_15_20s] [smallint] NULL,
	[aban_20_25s] [smallint] NULL,
	[aban_25_30s] [smallint] NULL,
	[aban_30_35s] [smallint] NULL,
	[aban_35_40s] [smallint] NULL,
	[aban_40_45s] [smallint] NULL,
	[aban_mayor_45s] [smallint] NULL,
	[cont_0_5s] [smallint] NULL,
	[cont_5_10s] [smallint] NULL,
	[cont_10_15s] [smallint] NULL,
	[cont_15_20s] [smallint] NULL,
	[cont_20_25s] [int] NULL,
	[cont_25_30s] [int] NULL,
	[cont_30_35s] [int] NULL,
	[cont_35_40s] [int] NULL,
	[cont_40_45s] [int] NULL,
	[cont_mayor_45s] [int] NULL,
	[cont_antes_15s] [int] NULL,
	[cont_post_umbral] [smallint] NULL,
	[aux_break] [int] NULL,
	[aux_backoffice] [smallint] NULL,
	[aux_refrigerio] [int] NULL,
	[aux_backoffice_2] [smallint] NULL,
	[aux_devo_grupal] [int] NULL,
	[aux_devo_individual] [smallint] NULL,
	[aux_rrhh] [int] NULL,
	[errores_criticos] [smallint] NULL,
 CONSTRAINT [PK_metrica_contact_center] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
