-- Table [dbo].[Ausentismo]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Ausentismo]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Ausentismo](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[CAMPAÑA] [varchar](max) NULL,
	[PROGRAMADOS] [smallint] NULL,
	[AUSENTES] [smallint] NULL,
	[HORAS PROGRAMADAS] [float] NULL,
	[CUMPLIMIENTO] [float] NULL,
	[CUMPLIMIENTO NETO] [float] NULL,
	[DESVÍO] [float] NULL,
	[DESVÍO (HS)] [float] NULL,
	[ADHERENCIA] [float] NULL,
	[AUSENTISMO] [float] NULL,
	[AUS. PLANIFICADO] [float] NULL,
	[AUS. NO PLANIFICADO] [float] NULL,
	[FECHA] [date] NULL,
 CONSTRAINT [PK_Ausentismo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
