-- Table [dbo].[Convenios]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Convenios]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Convenios](
	[Convenio ID] [smallint] IDENTITY(1,1) NOT NULL,
	[Convenio] [varchar](max) NULL,
 CONSTRAINT [PK_Convenios] PRIMARY KEY CLUSTERED 
(
	[Convenio ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
