-- Table [dbo].[CSV Horarios]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSV Horarios]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CSV Horarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Horario] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CSV Horarios] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
