-- Table [dbo].[dias_sem]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[dias_sem]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[dias_sem](
	[id] [tinyint] NOT NULL,
	[dia] [varchar](10) NULL,
 CONSTRAINT [PK_dias_sem] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
