-- Table [orion].[Campanas]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[orion].[Campanas]') AND type in (N'U'))
BEGIN
CREATE TABLE [orion].[Campanas](
	[Id_Campana] [int] IDENTITY(1,1) NOT NULL,
	[Nombre_Campana] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Campana] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
