-- Table [orion].[Canals]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[orion].[Canals]') AND type in (N'U'))
BEGIN
CREATE TABLE [orion].[Canals](
	[Id_Canal] [int] IDENTITY(1,1) NOT NULL,
	[Nombre_Canal] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Canal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
